server:
  port: 8083

spring:
  config:
    import: optional:file:.env[.properties]
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
grpc:
  client:
    GLOBAL:
      address: ${GRPC_HOST}
      negotiation-type: plaintext

fetch:
  batch-size: ${BATCH_SIZE}

